version: '3.8'
services:
  sql-absensi:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-absensi
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sql_absensi_data:/var/opt/mssql

volumes:
  sql_absensi_data:
